title: Ranjan Kumar Das
email: d.ranjan@iitg.ac.in 
description: > # this means to ignore newlines until "baseurl:"
  

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-architect
