title: Test Page before Final Changes
author: Debasish
email: drdebmath[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the site description header.

# social links
twitter_username: drdebmath
github_username:  drdebmath

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
